AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam app
Globals:
  Function:
    Timeout: 60
    MemorySize: 3008
    Runtime: nodejs14.x
Resources:
  LightouseLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: post
